apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  targetNamespace: cattle-system
  set:
    hostname: k3s.jrkripto.vip
    ingress.tls.source: letsEncrypt
    letsEncrypt.email: ksksertac@gmail.com
    letsEncrypt.ingress.class: nginx