apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapi-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik          # ✅ Yeni ekledik
  tls:
  - hosts:
      - k3sapi.jrkripto.vip
    secretName: testapi-tls
  rules:
  - host: k3sapi.jrkripto.vip
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testapi
            port:
              number: 8080
