apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapi-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"               # ✅ doğru class
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # sertifika için
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
      - k3sapi.jrkripto.vip
    secretName: testapi-tls
  rules:
  - host: k3sapi.jrkripto.vip
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testapi
            port:
              number: 8080
