apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapi-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"                 # Traefik yönlendirici
    cert-manager.io/cluster-issuer: "letsencrypt-prod"     # Let's Encrypt TLS
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
      - k3sapi.jrkripto.vip                                # 🔥 Yeni domain
    secretName: testapi-tls
  rules:
  - host: k3sapi.jrkripto.vip                              # 🔥 Yeni domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testapi
            port:
              number: 8080
