apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: default
spec:
  selector:
    app: test-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
